# Generated by Django 5.2.17 on 2026-09-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('User canceled', 'User canceled'), ('Refunded', 'Refunded')], default='Initiated', max_length=30)),
                ('amount_paisa', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_transactions', to='orders.order')),
            ],
        ),
    ]
